### PR TITLE
✨ Enable EdgePlacement to say "create-only"

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR expands the EdgePlacement API so that an EdgePlacement can apply the "create-only" setting to selected objects. This is good because it enables the "create-only" setting to be applied to third-party workload objects.

## Related issue(s)

This is built on #1277 and will be rebased if that merges first.

This is part of the campaign in #1274

### CODE REVIEW

**Comment by clubanderson** [comment]
If our syncer reacts to "overwrite downsync" true or false, then our edgeplacement should match that terminology. We should not have two different terms to mean the same thing.

**Comment by MikeSpreitzer** [comment]
Yes, consistency is good.  Consistency with ArgoCD, FluxCD, and OCM in the naming of this concept would also be good, if they happen to have the same concept and call it by the same name.

**Comment by MikeSpreitzer** [comment]
In the "application" side of OCM (not the "policy" side), they use the term "create only" for this concept, albeit motivated by a different use case.  See https://open-cluster-management.io/concepts/manifestwork/#resource-race-and-adoption

**Comment by clubanderson** [comment]
Right. We are not OCM. We use overwrite downsync.

**Pull request closed without merging**
