### PR TITLE
✨ openssf badge needed for clomonitor rating increase

### PR DESCRIPTION
**Pull request by clubanderson**
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
A preview would be helpful. You can explicitly request a run of the "Generate and Push Docs" workflow in your fork. If you had named the branch here `doc-<something>` then it would have been done automatically.

**Comment by MikeSpreitzer** [comment]
Preview at https://clubanderson.github.io/kubestellar/openssf-part1/readme/ ? Does this PR change that particular page? I do not see anything about 'bestpractices' there.

**Comment by clubanderson** [comment]
I updated the Readme for the repo. Not the Readme in the docs

**Comment by MikeSpreitzer** [comment]
In this case the preview is on GitHub not the website; see https://github.com/clubanderson/kubestellar/tree/openssf-part1

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
