### PR TITLE
🐛 Use realpath to see through symlinks

### LINKED ISSUE #1152: bug: scripts that navigate from bin to peer directories vs symlinks
### Describe the bug

kubectl-kubestellar-deploy
`kubestellar init`

expect helm chart, config directory to be peer of bin. symlinks mess this up.

### Steps To Reproduce

Try kubectl-kubestellar-deploy after the brew install, for example. Or try any example with a symlink involved.

### Expected Behavior

stuff gets found

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR injects usage of `realpath` into scripts that navigate from `$something/bin` to `$something/config` or `$something/core-helm-chart` because sometimes that `bin` is a symlink and the `config` or `core-helm-chart` is adjacent to where that symlink points.

This PR also removes a redundant variable holding the `bin` pathname.

## Related issue(s)

Fixes #1152

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
Successfully tested on my Mac (OS 13.5, Ventura) using deployment of core in a kind cluster using the v0.8.0 core image. That is, I tested that `kubectl-kubestellar-deploy` works, did not test the navigation in `kubestellar init`. The CI test of example1 covered the latter.

**Review by clubanderson — COMMENTED** [review]
/lgtm

**Comment by MikeSpreitzer** [comment]
Successful test with:
- deploy core to kind cluster, using image built from first commit here (`quay.io/kubestellar/kubestellar:v0.9.0-alpha.1.git1f0e2cc-clean`)
- `make userbuild` rather than `make build` to get user's executables
- create a special `bin` full of symlinks to the executables and put that special `bin` on the `$PATH` (this is parallel to what brew install does, as is demonstrated with the `go` binary)

The attached typescript shows most of what was done (including a few mistakes and recoveries); some of the setup (mostly kind) was done in a different shell.

[test1156.log](https://github.com/kubestellar/kubestellar/files/13034356/test1156.log)

**Comment by MikeSpreitzer** [comment]
Prow commands do not touch GitHub Actions

**Comment by MikeSpreitzer** [comment]
Let's see what close and re-open does.

**Comment by MikeSpreitzer** [comment]
Let's see if this retries the GitHub workflows.

**Review by clubanderson — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
