### PR TITLE
:sparkles: deleted unused code

### PR DESCRIPTION
**Pull request by vMaroon**
## Summary
Deleted unused functions and constants, set unused function parameters to underscore.

This was done in order to remove deletion noise from the to-be-made PR for issue #1730, which will delete a lot of functions.

## Related issue(s)
#1730

### CODE REVIEW

**Review by MikeSpreitzer — COMMENTED** [review]
/lgtm
Not sure about how we want to interleave this with the other PRs in flight.

**Comment by vMaroon** [comment]
@MikeSpreitzer technically this is of the lowest priority, but on the other hand rebasing on it should have no conflicts. I think what's most important is to get it through before my next. Up to you.

**Comment by MikeSpreitzer** [comment]
Now that #1735 has merged, I think it is OK to merge this next (after the needed rebase, of course). It should have little interaction with #1707.

**Comment by vMaroon** [comment]
rebased

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
/approve
Thanks!

**Pull request merged**
