### PR TITLE
:seedling: Update README.md contributor section

### PR DESCRIPTION
**Pull request by rchen-devv**
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by clubanderson** [comment]
/ok-to-test

@rchen-devv you need to sign this PR

**Comment by ezrasilvera** [comment]
@rchen-devv Thanks for the PR.  I think we should actually remove the contributors links from this README.  It's not a common thing to maintain contributor list as part of the docs.  
Anyone who is interested can find all contributors in the regular place: https://github.com/kubestellar/kubestellar/graphs/contributors

**Comment by ezrasilvera** [comment]
something went wrong with the PR, the commit doesn't seem to belong to this PR

**Pull request closed without merging**
