### PR TITLE
🌱 Update default core image tag to build of PR 1111

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates the core image tag used by `kubectl kubestellar deploy` to a build of the latest (as of now) core code.

## Related issue(s)

This picks up the changes in #1111 .

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
/cc @francostellari 
/cc @clubanderson 
/cc @dumb0002 
@yana1205

**Comment by yana1205** [comment]
Is the right image `v0.8.0-alpha.9.42d07da-clean` not the v0.9.0?
It seems that quay.io/kubestellar/kubestellar:v0.9.0-alpha.9.42d07da-clean doesn't exist yet. 

If it will be created after this PR is merged, looks good to me.

**Comment by MikeSpreitzer** [comment]
We have not made release `v0.8.0` yet. A semantic version like `v0.8.0-alpha.9.42d07da-clean` _precedes_ `v0.8.0`. If you look at the ordering rules at https://semver.org/ you will see that I am using the pattern `v${upcoming_release}-alpha.${count}.${gittery}`, counting builds upward, so that the semver ordering rules give the right result and the semver contains the git commit.

**Comment by yana1205** [comment]
OK, thanks for clarifying it.
`upcoming_release` is v0.8.0. You set `image_tag=v0.9.0-alpha.9.42d07da-clean` but is it typo of `image_tag=v0.8.0-alpha.9.42d07da-clean`?

**Comment by MikeSpreitzer** [comment]
@yana1205 : Oh, typo! Thanks for catching that. Fixed now.

**Pull request merged**
