### PR TITLE
✨ Upgrade KubeFlex dependency to release 0.6.3

### LINKED ISSUE #2389: Raise required version of KubeFlex to avoid accidental confusion
https://docs.kubestellar.io/unreleased-development/direct/pre-reqs/#software-prerequisites-for-using-kubestellar says the minimum version of KubeFlex to use is 0.6.1.

We have had confusion caused by the hidden state that `kflex` maintains in the user's kubeconfig file, the preference.extension that holds the name of the context to use when accessing the hosting cluster. Some users somehow got the wrong value in there, or never got any value in there, and it caused them no end of trouble. See #2257 for an example result of the confusion.

The behavior of `kfex` is more assertive in release 0.6.2. I think that the user confusion that we had would not have happened if the users had been using release 0.6.2.

### LINKED ISSUE #2445: bug: CI uses outdated version of kubeflex
### Describe the bug

O crud. All the github Actions workflows install kubeflex release 0.4.2, even though https://github.com/kubestellar/kubestellar/blob/main/docs/content/direct/pre-reqs.md#software-prerequisites-for-using-kubestellar says that the minimum required version is 0.6.1.

### Steps To Reproduce

Look at CI runs from 0.24.0-rc.1

### Expected Behavior

Using kubeflex features that are in 0.6.1 work even if those features are missing from earlier releases.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR bumps the release of KubeFlex that KubeStellar requires, from 0.6.1 to 0.6.3, to pick up recent developments in KubeFlex.

This PR also adds a section to the release process document describing how to bump this dependency.

## Related issue(s)

Fixes #2389 
Fixes #2445

### CODE REVIEW

**Comment by francostellari** [comment]
@MikeSpreitzer since these changes are only needed in the context of the new merged chart. I strongly suggest to leave it alone and have the changes made by that PR to avoid creating further merge conflicts.

**Comment by MikeSpreitzer** [comment]
The force-push to dfcff1273 is a rebase onto `main`.

**Comment by MikeSpreitzer** [comment]
I tried to dance around #2465 to avoid merge conflicts, but do not see how to avoid git reporting a merge conflict due to that PR's not removing v06.1 of kubeflex from go.sum (in the same commit that it adds v0.6.3).

**Pull request merged**
