### PR TITLE
✨ Add final state dump of Deployment objs in WEC(s)

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR extends the state dumping at the end of the e2e tests to include the Deployment objects on the WEC(s).

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by effi-ofer** [comment]
Again I am late to the party. You guys never sleep :P.  I think the multi cluster test should dump both cluster1 and cluster2 deployment.  I'll add it via a separate PR when I have a few spare moments.

**Comment by MikeSpreitzer** [comment]
@effi-ofer : I think this PR added that? Am I misunderstanding something?

**Comment by effi-ofer** [comment]
You're right.  I must have been temporarily blind.

**Pull request merged**
