### PR TITLE
📖  Update to troubleshooting guide for issues with default settings in rancher desktop

### LINKED ISSUE #2487: bug: installing kubestellar getting started on kind with rancher desktop
### Describe the bug

I get an error when I try to install kubestellar on kind. Kind is runner with dockerd from rancher desktop. The error I get is from Kind when our getting started script (or automated demo environment bash script) is trying to create the second cluster (cluster 2). The error looks like this...

```
Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂
Context "kind-cluster1" renamed to "cluster1".
Error: hub oriented command should not running against non-hub cluster
Creating cluster "cluster2" ...
 ✓ Ensuring node image (kindest/node:v1.27.1) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✗ Starting control-plane 🕹️
Deleted nodes: ["cluster2-control-plane"]
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged cluster2-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
Command Output: I1008 16:11:20.743111     134 initconfiguration.go:255] loading configuration from "/kind/kubeadm.conf"
W1008 16:11:20.743835     134 initconfiguration.go:332] [config] WARNING: Ignored YAML document with GroupVersionKind kubeadm.k8s.io/v1beta3, Kind=JoinConfiguration
[init] Using Kubernetes version: v1.27.1
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I1008 16:11:20.748175     134 certs.go:112] creating a new certificate authority for ca
[certs] Generating "ca" certificate and key
I1008 16:11:20.789452     134 certs.go:519] validating certificate period for ca certificate
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [cluster2-control-plane kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local localhost] and IPs [10.96.0.1 172.18.0.4 127.0.0.1]
[certs] Generating "apiserver-kubelet-client" certificate and key
I1008 16:11:21.009079     134 certs.go:112] creating a new certificate authority for front-proxy-ca
```

### Steps To Reproduce

to reproduce this
1) install rancher desktop
2) install kind
3) install all other kubestellar pre-reqs
4) run through kubestellar getting started (or run the kubestellar demo environment setup bash script)
5) observe completed kubeflex installation
6) observe wait for ITS1 and WDS1 creation
7) observe creation of cluster1 remote cluster
8) wait for cluster2 remote cluster to create successfully

fail...

### Expected Behavior

cluster 2 should create successfully

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by clubanderson**
## Related issue(s)

Fixes #2487

### CODE REVIEW

**Review by KPRoche — COMMENTED** [review]
/lgtm

**Comment by MikeSpreitzer** [comment]
PR #2486 introduces a section for known issues. It seems, to me, to be an appropriate vertex in the doc organization.

The amount of material introduced here is quite large, comparable to the whole of the pre-existing troubleshooting document. Maybe put the new material here in its own doc and link from the known issues section?

**Comment by MikeSpreitzer** [comment]
The content introduced here is only a little specific to Rancher Desktop. Very similar remarks apply to other ways of getting a container runtime on a Mac. Can this be revised to be more broadly useful?

**Review by MikeSpreitzer — APPROVED** [review]
My comments can be addressed in later PRs.

/lgtm
/approve
Thanks!

**Pull request merged**
