### PR TITLE
🌱 Restore other docs-ecutable workflows for legacy releases, for main

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR narrows the applicability of the remaining docs-ecutable workflows to legacy releases, in the workflow definitions in the `main` branch.

This is part of addressing #1585 

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by ezrasilvera** [comment]
@MikeSpreitzer Is it indeed necessary to enable all workflows for the legacy release ?  I imagine that for validation tests 1 or 2 will be enough. It's adding a support and maintenance complexity to have so many workflows that are not part of our main anymore. 
Can we move all to `legacy` sub directory ?  Or prefix all with `legacy-`  ?

**Comment by ezrasilvera** [comment]
> @MikeSpreitzer Is it indeed necessary to enable all workflows for the legacy release ? I imagine that for validation tests 1 or 2 will be enough. It's adding a support and maintenance complexity to have so many workflows that are not part of our main anymore. Can we move all to `legacy` sub directory ? Or prefix all with `legacy-` ?

UPDATE - so apparently github workflows still doesn't support sub-folders :(   So maybe just prefix ?

**Comment by MikeSpreitzer** [comment]
@ezrasilvera : we seem to have some interest in maintaining the release-0.14 branch, so that is why I am making the workflows that test a release usable.

**Comment by MikeSpreitzer** [comment]
I suspect that renaming them in `main` will also require renaming them in `release-0.14` because for _some_ --- and not _all_ --- triggering events, what matters is what is in the relevant PR or branch rather than `main`. @clubanderson can you clarify?

**Pull request merged**
