### PR TITLE
✨ Bump latest version in VERSION to 0.4.0

### PR DESCRIPTION
**Pull request by francostellari**
## Summary

Bump `latest` version in VERSION to v0.4.0
Stay `stable` version at v0.3.1

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by clubanderson** [comment]
and, btw, what is this file used for?

**Comment by MikeSpreitzer** [comment]
@clubanderson: we have discussed using this file in place of parsing the HTML that GitHub chooses to serve up when someone asks it about the latest release.  This usage is starting in #764

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
/approve

**Comment by clubanderson** [comment]
@MikeSpreitzer @francostellari why is there 'stable' and 'latest'?  Our 'main' branch is used as 'latest' but there is no GH release that points at 'main'.  The 'latest' and 'stable' are always going to be the most recent release.  So why do we need 2 pointers in this file?

**Pull request merged**
