### PR TITLE
🌱 renamed imbs to transport in all places

### PR DESCRIPTION
**Pull request by nirrozenbaum**
## Related issue(s)

Fixes #

#1557

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
I thought the new name is "Inventory and Transport Space" (ITS).

**Comment by pdettori** [comment]
> I thought the new name is "Inventory and Transport Space" (ITS).

I thought the same. Until we come up with a solution for decoupling the inventory from the transport (which may happen with adoption of SIG MC inventory) the inventory and transport are still tightly coupled together

**Comment by nirrozenbaum** [comment]
we have transport space that includes the transport specifics and should have inventory space that includes the KS unified representation of the clusters (with no relation of which transport was selected).
transport space includes also the cluster representation that is specific to the transport (in our case, ManagedCluster CR which is specific to OCM).
inventory space should include the KS representation of the clusters which is calculated from the OCM MC.
Inventory space is out of version 0.20, but we need to leave room for adding inventory space once inventory is added.

**Comment by nirrozenbaum** [comment]
btw, the reason for this PR is because we talked about this in our of the calls and the team decided to do #1557 on phase1.
(prepare for introducing inventory after phase1)

**Comment by MikeSpreitzer** [comment]
I do not recall discussing #1557 

In release 0.20 we _do_ have inventory. It is in the same space as the transport. That is why it makes sense to call it the "Inventory and Transport Space".

**Comment by nirrozenbaum** [comment]
I assume one of us missed something, cause issue #1557 was labeled with phase1 (we went over this item as part of going over all items).

I see that we don't have consensus for this atm, so I can close PR for now and we can get back to this when we do the inventory work.

**Comment by nirrozenbaum** [comment]
closing this PR for now.
will be handled as part of the inventory work (when we split transport and inventory).

**Pull request closed without merging**
