### PR TITLE
⚠️ Partially converge old and new placement Kinds

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR does some convergence between the old and new placement Kinds.

This PR _only_ includes the IDL change. How do I update the generated files?

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
Note that in KubeStellar 0.15 and earlier there is a less expressive way of identifying upsynced objects than of identifying downsynced ones. Specifically, the test for upsynced objects could only examine immutable attributes. This has the advantage that it can be applied without having the objects in hand. For example, this supports answering the question "what if an object matches for both downsync and upsync?". I chose the answer that upsync takes precedence (https://github.com/kubestellar/kubestellar/blob/v0.15.0/pkg/apis/edge/v2alpha1/edge-placement.go#L78), because thinking of use cases it seemed the more useful choice (broad downsync criteria, with holes punched for upsync). But punching the holes in downsync is clearest if this does not depend on mutable object content (i.e., labels).

**Comment by MikeSpreitzer** [comment]
How do I make the container image, helm chart, and KubeFlex PostCreateHook to test this PR? Or test without building some or all of those?

**Comment by pdettori** [comment]
@MikeSpreitzer if you have a running ks 0.20 environment you may just scale to 0 the deployed kslight controller in the wds1-system namespace and then run the controller with `make run` - that should be good enough to test. To make the helm chart, you may use `make chart`. To do code generation (at this time only deep copy code, as there is not yet client code gen ) just do `make generate`.  I will open an issue and PR to add a makefile command for building the image, but if you want to build before then here is how to use ko for that:

```
export KO_DOCKER_REPO=ko.local
ko build -B  ./cmd/kubestellar-operator -t 0.1.0 --platform linux/amd64,linux/arm64
```

I am still in the process of renaming the image name in the relevant files.

**Comment by MikeSpreitzer** [comment]
@pdettori : thanks.  There are already some relevant Issues, see #1531 and #1532 .

**Comment by MikeSpreitzer** [comment]
@pdettori : I found that `make manifests` is needed to update the CRDs.

**Comment by MikeSpreitzer** [comment]
`make run` looks like it assumes something about the current kube client configuration, or requires `$(ARGS)` to establish something.

**Comment by pdettori** [comment]
@MikeSpreitzer yes, correct, you need also to run `make manifests` to generate the CRDs.

As for `make run`, currently the controller manager does some discovery by looking at controlplanes that have a specific label that identifies them with a role of wds or imbs. If there is only one with a role of wds, it just uses it, but if there is more then one you need to provide the wds name to point to. Therefore, $(ARGS) should be used to pass `--wds-name` if your env has more than one WDS (the  --wds-name is always used when controller is started by the KubeFlex post-create-hook)

**Comment by MikeSpreitzer** [comment]
I find _two_ containers in the kslight-controller-manager `Deployment`, and more arguments given to the actual controller-manager container.

```
mspreitz@mjs13 kubestellar % kubectl --context kind-kubeflex get deployments -n wds1-system kslight-controller-manager -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: kslight
    meta.helm.sh/release-namespace: wds1-system
  creationTimestamp: "2024-01-12T20:17:09Z"
  generation: 2
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: kslight
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: kslight
    control-plane: controller-manager
  name: kslight-controller-manager
  namespace: wds1-system
  resourceVersion: "6716"
  uid: a9d1c235-6daf-4c16-b51d-dc288f52b3ee
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      creationTimestamp: null
      labels:
        control-plane: controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
                - ppc64le
                - s390x
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --wds-name=wds1
        image: ghcr.io/kubestellar/kubeflex/kslight-operator:0.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: manager
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: kslight-controller-manager
      serviceAccountName: kslight-controller-manager
      terminationGracePeriodSeconds: 10
status:
  conditions:
  - lastTransitionTime: "2024-01-12T20:17:30Z"
    lastUpdateTime: "2024-01-12T20:17:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-01-12T20:17:09Z"
    lastUpdateTime: "2024-01-12T20:17:30Z"
    message: ReplicaSet "kslight-controller-manager-64c579bff4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
```

**Comment by MikeSpreitzer** [comment]
Running this PR's controller-manager failed, due to the conflict in the CRD. Following is stdout+stderr.

```
2024-01-12T16:01:53-05:00	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
2024-01-12T16:01:53-05:00	INFO	setup	Getting config for WDS	{"name": "wds1"}
2024-01-12T16:01:53-05:00	INFO	setup	using label	{"key": "kflex.kubestellar.io/cptype", "value": "wds"}
2024-01-12T16:01:53-05:00	INFO	setup	waiting for cp with label	{"key": "kflex.kubestellar.io/cptype", "value": "wds"}
2024-01-12T16:01:53-05:00	INFO	setup	Got config for WDS	{"name": "wds1"}
2024-01-12T16:01:53-05:00	INFO	setup	Getting config for IMBS
2024-01-12T16:01:53-05:00	INFO	setup	waiting for cp with label	{"key": "kflex.kubestellar.io/cptype", "value": "imbs"}
2024-01-12T16:01:53-05:00	INFO	setup	Got config for IMBS	{"name": "imbs1"}
2024-01-12T16:01:53-05:00	INFO	applying crd	{"name": "placements.edge.kubestellar.io"}
2024-01-12T16:01:53-05:00	ERROR	setup	error starting the placement controller	{"error": "Apply failed with 1 conflict: conflict with \"kslight\": .spec.versions"}
main.main
	/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/cmd/kubestellar-operator/main.go:139
runtime.main
	/opt/homebrew/Cellar/go/1.21.6/libexec/src/runtime/proc.go:267
exit status 1
```

**Comment by MikeSpreitzer** [comment]
FYI, I tried this but it has not returned yet:

```
mspreitz@mjs13 kubestellar % kubectl --context wds1 delete crds placements.edge.kubestellar.io
customresourcedefinition.apiextensions.k8s.io "placements.edge.kubestellar.io" deleted
```

**Comment by MikeSpreitzer** [comment]
In a separate shell I added the following. Now both are hung.

```
mspreitz@mjs13 ~ % kubectl --context wds1 delete placements nginx-placement
placement.edge.kubestellar.io "nginx-placement" deleted
```

**Comment by MikeSpreitzer** [comment]
In a third shell, I see that the Placement is still there. Hanging around because the non-existent controller is not removing the finalizer, I assume.

```
mspreitz@mjs13 ~ % kubectl --context wds1 get placements -o yaml
apiVersion: v1
items:
- apiVersion: edge.kubestellar.io/v1alpha1
  kind: Placement
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"edge.kubestellar.io/v1alpha1","kind":"Placement","metadata":{"annotations":{},"name":"nginx-placement"},"spec":{"clusterSelectors":[{"matchLabels":{"location-group":"edge"}}],"downsync":[{"labelSelectors":[{"matchLabels":{"app.kubernetes.io/name":"nginx"}}]}]}}
    creationTimestamp: "2024-01-12T20:35:28Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2024-01-12T21:04:36Z"
    finalizers:
    - placement.kubestellar.io/kscontroller
    generation: 2
    name: nginx-placement
    resourceVersion: "2211"
    uid: d4b7b22a-037c-423b-9ed8-1c64b68ea55c
  spec:
    clusterSelectors:
    - matchLabels:
        location-group: edge
    downsync:
    - labelSelectors:
      - matchLabels:
          app.kubernetes.io/name: nginx
kind: List
metadata:
  resourceVersion: ""
```

**Comment by MikeSpreitzer** [comment]
So I scaled back up the controller-manager Deployment to unwedge. The CRD and Placement deletions completed. Now the controller-manager is running, and the CRD is absent! That seems like a bug, but not a blocker for this testing.

**Comment by pdettori** [comment]
@MikeSpreitzer that is correct, it is because the ks controller manager scaffolding has been created initially with Kubebuilder, which adds the proxy container and set up health probe and metrics. The additional parameters are only used when running in-cluster (thus not with `make run`) and are defined in https://github.com/kubestellar/kubestellar/blob/fb817e2f99e76c3b8b74bcfe40388d09c998f1ff/cmd/kubestellar-operator/main.go#L63-L64

**Comment by MikeSpreitzer** [comment]
What does that proxy container do? Why should I be able to test without it?

**Comment by pdettori** [comment]
> What does that proxy container do? Why should I be able to test without it?

@MikeSpreitzer : 
Some info from Kubebuilder:

In a controller created using Kubebuilder, the proxy container, often referred to as the kube-rbac-proxy, is deployed as a sidecar container in the [manager pod](https://book-v1.book.kubebuilder.io/beyond_basics/controller_metrics.html)
Its primary role is to secure the metrics endpoint of the controller. 

The kube-rbac-proxy uses Kubernetes Role-Based Access Control (RBAC) to authenticate and authorize access to the metrics [endpoint](https://book.kubebuilder.io/reference/metrics.html). This ensures that only authorized entities can access the metrics exposed by the controller.

By default, Kubebuilder generates YAML manifests that deploy this proxy container and set up the necessary RBAC rules. This helps to enhance the security of the controller by protecting its metrics endpoint.

**Comment by MikeSpreitzer** [comment]
I have successfully (I think) tested this PR with https://github.com/kubestellar/kubestellar/tree/ks-0.20/docs/content/v0.20#scenario-1---multi-cluster-workload-deployment-with-kubectl modified as follows.
- Delete the Placement object in wds1.
- Scale the kslight-controller-manager Deployment in namespace wds1-system, kubeconfig context kind-kubeflex, to 0 replicas.
- Delete the placements.edge.kubestellar.io CRD in kubeconfig context wds1.
- `go run ./cmd/kubestellar-operator/main.go --wds-name=wds1 &> /tmp/ko.log`

However, the log from that controller-manager contains some error messages.

```
2024-01-12T16:13:32-05:00	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
2024-01-12T16:13:32-05:00	INFO	setup	Getting config for WDS	{"name": "wds1"}
2024-01-12T16:13:32-05:00	INFO	setup	using label	{"key": "kflex.kubestellar.io/cptype", "value": "wds"}
2024-01-12T16:13:32-05:00	INFO	setup	waiting for cp with label	{"key": "kflex.kubestellar.io/cptype", "value": "wds"}
2024-01-12T16:13:32-05:00	INFO	setup	Got config for WDS	{"name": "wds1"}
2024-01-12T16:13:32-05:00	INFO	setup	Getting config for IMBS
2024-01-12T16:13:32-05:00	INFO	setup	waiting for cp with label	{"key": "kflex.kubestellar.io/cptype", "value": "imbs"}
2024-01-12T16:13:32-05:00	INFO	setup	Got config for IMBS	{"name": "imbs1"}
2024-01-12T16:13:32-05:00	INFO	applying crd	{"name": "placements.edge.kubestellar.io"}
2024-01-12T16:13:33-05:00	INFO	crd name accepted	{"name": "placements.edge.kubestellar.io"}
I0112 16:13:34.902365    7190 request.go:697] Waited for 1.199551334s due to client-side throttling, not priority and fairness, request: GET:https://wds1.localtest.me:9443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0
2024-01-12T16:13:35-05:00	INFO	waiting for caches to sync
2024-01-12T16:13:38-05:00	INFO	setup	starting manager
2024-01-12T16:13:38-05:00	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
2024-01-12T16:13:38-05:00	INFO	starting server	{"path": "/metrics", "kind": "metrics", "addr": "[::]:8080"}
2024-01-12T16:13:39-05:00	INFO	All caches synced
2024-01-12T16:13:39-05:00	INFO	Starting workers	{"count": 4}
2024-01-12T16:13:39-05:00	INFO	Started workers
2024-01-12T16:13:39-05:00	INFO	All caches synced
2024-01-12T16:13:39-05:00	INFO	Starting workers	{"count": 4}
2024-01-12T16:13:39-05:00	INFO	Started workers
Matched key edge.kubestellar.io/v1alpha1/Placement
2024-01-12T16:15:24-05:00	INFO	Matched	{"object": "[] namespace/nginx", "for placement": "nginx-placement"}
2024-01-12T16:15:24-05:00	INFO	Matched	{"object": "[nginx] deployment.apps/nginx-deployment", "for placement": "nginx-placement"}
2024-01-12T16:15:24-05:00	INFO	Delivering	{"object": "[nginx] deployment.apps/nginx-deployment", "to clusters": ["cluster1", "cluster2"]}
2024-01-12T16:15:24-05:00	INFO	Delivering	{"object": "[] namespace/nginx", "to clusters": ["cluster1", "cluster2"]}
2024-01-12T16:15:24-05:00	ERROR	Error delivering object to mailbox	{"error": "Apply failed with 1 conflict: conflict with \"kslight\": .spec.workload.manifests"}
github.com/kubestellar/kubestellar/pkg/placement.deliverObjectToManagedClusters
	/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/pkg/placement/manifest.go:39
github.com/kubestellar/kubestellar/pkg/placement.(*Controller).reconcile
	/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/pkg/placement/controller.go:444
github.com/kubestellar/kubestellar/pkg/placement.(*Controller).processNextWorkItem.func1
	/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/pkg/placement/controller.go:366
github.com/kubestellar/kubestellar/pkg/placement.(*Controller).processNextWorkItem
	/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/pkg/placement/controller.go:376
github.com/kubestellar/kubestellar/pkg/placement.(*Controller).runWorker
	/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/pkg/placement/controller.go:331
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:259
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:226
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:227
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:204
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:259
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:170
2024-01-12T16:15:24-05:00	ERROR	Error delivering object to mailbox	{"error": "Apply failed with 1 conflict: conflict with \"kslight\": .spec.workload.manifests"}
github.com/kubestellar/kubestellar/pkg/placement.deliverObjectToManagedClusters
	/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/pkg/placement/manifest.go:39
github.com/kubestellar/kubestellar/pkg/placement.(*Controller).reconcile
	/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/pkg/placement/controller.go:444
github.com/kubestellar/kubestellar/pkg/placement.(*Controller).processNextWorkItem.func1
	/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/pkg/placement/controller.go:366
github.com/kubestellar/kubestellar/pkg/placement.(*Controller).processNextWorkItem
	/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/pkg/placement/controller.go:376
github.com/kubestellar/kubestellar/pkg/placement.(*Controller).runWorker
	/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/pkg/placement/controller.go:331
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:259
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:226
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:227
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:204
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:259
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
	/Users/mspreitz/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/backoff.go:170
```

**Comment by pdettori** [comment]
> In a third shell, I see that the Placement is still there. Hanging around because the non-existent controller is not removing the finalizer, I assume.

@MikeSpreitzer yes, Placement uses a finalizer to allow removing manifests (or labels, for overlapping placements) for objects associated with that placement.  Therefore, the finalizer block deletion unless the controller is running.

**Comment by MikeSpreitzer** [comment]
Deleting the Placement in wds1 worked, the controller-manager deleted the ManifestWork objects in imbs1.

```
2024-01-12T16:26:03-05:00	INFO	Trying to delete manifest	{"manifest name": "v1-namespace--nginx", "namespace": "cluster1", "for placement": "nginx-placement"}
2024-01-12T16:26:03-05:00	INFO	Trying to delete manifest	{"manifest name": "v1-namespace--nginx", "namespace": "cluster2", "for placement": "nginx-placement"}
2024-01-12T16:26:03-05:00	INFO	Trying to delete manifest	{"manifest name": "appsv1-deployment-nginx-nginx-deployment", "namespace": "cluster2", "for placement": "nginx-placement"}
2024-01-12T16:26:03-05:00	INFO	Trying to delete manifest	{"manifest name": "appsv1-deployment-nginx-nginx-deployment", "namespace": "cluster1", "for placement": "nginx-placement"}
E0112 16:26:03.277646    7190 controller.go:333] resource 'cluster2/appsv1-deployment-nginx-nginx-deployment' in work queue no longer exists
E0112 16:26:03.283448    7190 controller.go:333] resource 'cluster1/appsv1-deployment-nginx-nginx-deployment' in work queue no longer exists
```

Then I re-created that Placement, and the controller-manager logged successful delivery of the ManifestWork objects.

```
2024-01-12T16:28:21-05:00	INFO	Matched	{"object": "[nginx] deployment.apps/nginx-deployment", "for placement": "nginx-placement"}
2024-01-12T16:28:21-05:00	INFO	Matched	{"object": "[] namespace/nginx", "for placement": "nginx-placement"}
2024-01-12T16:28:21-05:00	INFO	Delivering	{"object": "[nginx] deployment.apps/nginx-deployment", "to clusters": ["cluster2", "cluster1"]}
2024-01-12T16:28:21-05:00	INFO	Delivering	{"object": "[] namespace/nginx", "to clusters": ["cluster1", "cluster2"]}
```

**Comment by pdettori** [comment]
> However, the log from that controller-manager contains some error messages.

The code that copies the manifest to the mailbox namespaces uses server side apply with the name of the manager `kslight`. Since initially you run from the published image for kslight, it probably applied with that name for the manager. But since then, the code has been re-factored to use `kubestellar` instead of `kslight` in all occurrences, therefore the conflict. You may just run `kubectl --context imbs1 delete -n cluster1 manifestworks --all`   and `kubectl --context imbs1 delete -n cluster2 manifestworks --all`, then re-start the controller with `make run` (the ks controller pod should be scaled down to 0)

**Comment by MikeSpreitzer** [comment]
A few nits that I noticed:
- two styles of logging was a surprise. I like getting the more precise timestamps.
- still some uses of "resource" where "object" is meant.
- The logging at manifest.go:39 does not identify the object or the mailbox involved.
- Is that really a conflict if both FieldMangers specify the same content?

**Comment by pdettori** [comment]
> So I scaled back up the controller-manager Deployment to unwedge. The CRD and Placement deletions completed. Now the controller-manager is running, and the CRD is absent! That seems like a bug, but not a blocker for this testing.

The controller check is the Placement CRD is present on the WDS at startup and installs it if it is not there. So after you started the controller, the CRD was automatically installed. This was done to simplify startup of the controller that has to run in the hosting cluster but needs a CRD in the WDS. The usual pattern of deploying CRD and controllers all in one cluster (the hosting cluster) would not work in this case. A user would have install the CRD pointing kubectl to the WDS and then install the controller in the hosting cluster. One main use case for this is the post-create-hook for kslight.

Note - the conflict in the applying of the CRD is once again due to the server side apply and the name of the manager used in the controller manager is different.

**Comment by pdettori** [comment]
> A few nits that I noticed:
> 
> * two styles of logging was a surprise. I like getting the more precise timestamps.
> * still some uses of "resource" where "object" is meant.
> * The logging at manifest.go:39 does not identify the object or the mailbox involved.
> * Is that really a conflict if both FieldMangers specify the same content?
> 
> I think those can be addressed in follow-on PRs.

@MikeSpreitzer agree, let's address these in other PRs. Do you have an example of the different styles of logging?

Re. FieldManager conflicts:

What I found is that if you change the FieldManager during a server-side apply operation, it could lead to conflicts. This is because the API server uses the FieldManager to determine who has ownership of a [field](https://kubernetes.io/docs/reference/using-api/server-side-apply/)

If a field that is managed by a different FieldManager is changed, the API server will throw an error. I suppose that there was some change in the CRD since you updated the Placement API types a bit for the convergence work, therefore the conflict was detected.

**Comment by MikeSpreitzer** [comment]
As a FieldManager name, "kubestellar" is not very distinctive, since it refers to the whole system. A better name would identify the particular controller involved.

The conflict I was asking about was the reported conflict in ManifestWork objects, whose CRD is not being modified here.

The two different styles of logging can be seen above in the log excerpt showing the reaction to deleting the Placement object.

**Comment by MikeSpreitzer** [comment]
Um, oops, forgot to include the doc update.  Coming soon...

**Pull request merged**
