### PR TITLE
📖 Make examples.md reference its own release instead of a past one

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR changes the tense of the examples document, to reference its own release (adding self-reference problems) rather than a past release.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by pdettori** [comment]
This looks good, should we also update `config/postcreate-hooks/kubestellar.yaml` as part of the same PR ?

**Comment by MikeSpreitzer** [comment]
The PCH does not have to be updated in the same PR. I would leave it separate.

**Review by pdettori — APPROVED** [review]
/lgtm

**Pull request merged**
