### PR TITLE
🌱 Restore other docs-ecutable workflows for legacy releases, for release-0.14

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR narrows what the remaining docs-ecutable workflows say they apply to, restricting them to legacy releases.

This addresses part of #1585 

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by ezrasilvera** [comment]
@MikeSpreitzer Is it indeed necessary to enable all workflows for the legacy release ? I imagine that for validation tests 1 or 2 will be enough. It's adding a support and maintenance complexity to have so many workflows that are not part of our main anymore.
Can we move all to legacy sub directory ? Or prefix all with legacy- ?

**Comment by ezrasilvera** [comment]
> @MikeSpreitzer Is it indeed necessary to enable all workflows for the legacy release ? I imagine that for validation tests 1 or 2 will be enough. It's adding a support and maintenance complexity to have so many workflows that are not part of our main anymore. Can we move all to legacy sub directory ? Or prefix all with legacy- ?

UPDATE - so apparently github workflows still doesn't support sub-folders :(   So maybe just prefix ?

**Comment by ezrasilvera** [comment]
@MikeSpreitzer do we still need this ?   If not please close.

**Comment by MikeSpreitzer** [comment]
I am not sure whether we will need this. It may depend on related things we do or do not do for non-legacy KubeStellar.

**Pull request merged**
