### PR TITLE
:bug: Update the "new bug" template

### PR DESCRIPTION
**Pull request by ezrasilvera**
Remove the old instructions for specific KS info collection, these instructions are not suitable for the new KS. For now, the general template asking for bug description, logs, and expected behavior is good enough.

## Related issue(s)

Fixes #

### CODE REVIEW

**Review by clubanderson — COMMENTED** [review]
/lgtm

**Comment by JonathanWentaoBao** [comment]
This should fix issue #2224

**Review by MikeSpreitzer — COMMENTED** [review]
I think that we should retain some remarks about collecting the relevant versions.
I think that we should retain some remarks about collecting kubeconfig state. We still have a system that is sensitive to obscure user state: the value of the `KUBECONFIG` envar, the current kubeconfig context.

**Review by MikeSpreitzer — APPROVED** [review]
Yes, we can restore the needed content in a follow-on PR.

/lgtm
/approve
Thanks!

**Pull request merged**
