### PR TITLE
✨ Add version checking to the check_pre_req script

### LINKED ISSUE #2492: feature: dependency checking script should check version
### Feature Description

It is a problem when the dependency checking script (hack/check_pre_req.sh) claims success but the dependency is at too old of a version.

### Proposed Solution

Make the dependency checking script check the versions.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

If this feature had been present then issue #2491 would not have been raised (the user would have been told that they have too old a version of kflex).

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR enhances `hack/check_pre_req.sh` to know what the minimum required version of each dependency is, and check that. This PR also enhances the pre-reqs doc to list all the minimum required versions.

I had to guess at some of the version requirements.

Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-check-versions/direct/pre-reqs/

## Related issue(s)

Fixes #2492 
This also completes the work on Issue 2491, which is already marked as complete (although I do not understand why).

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
The force-push above is a rebase onto `main` because #2524 has merged.

**Comment by MikeSpreitzer** [comment]
The force-push to c5ea9f3ba fixes the forward reference `[check-pre-req](#automated-check-of-prerequisites-for-kubestellar)` (that's the fixed version).

**Comment by MikeSpreitzer** [comment]
One could test the revised script as follows.

```console
mspreitz@mjs13 kubestellar % curl https://raw.githubusercontent.com/MikeSpreitzer/kcp-edge-mc/refs/heads/doc-check-versions/hack/check_pre_req.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7041  100  7041    0     0  73442      0 --:--:-- --:--:-- --:--:-- 74115
Checking pre-requisites for using KubeStellar:
✔ Docker (Docker version 27.2.1-rd, build cc0ee3e)
✔ kubectl (v1.29.2)
✔ KubeFlex (Kubeflex version: v0.7.1.25d62b6 2024-10-24T02:52:51Z)
✔ OCM CLI (:v0.9.0-0-g56e1fc8)
✔ Helm (v3.16.1)
Checking additional pre-requisites for running the examples:
✔ Kind (kind v0.22.0 go1.22.0 darwin/arm64)
✔ ArgoCD CLI (v2.10.1+a79e0ea)
Checking pre-requisites for building KubeStellar:
✔ GNU Make (GNU Make 3.81)
✔ Go (go version go1.23.2 darwin/arm64)
✔ KO (0.17.1)
```

**Comment by eaepstein** [comment]
lgtm

**Pull request merged**
