### PR TITLE
📖 Streamline release categorization

### LINKED ISSUE #2019: bug: weird stuff with latest and stable release pointers in the website
### Describe the bug

- https://docs.kubestellar.io/release-0.21.0/direct/examples/ tells the reader to "You're not viewing the stable release. Click here to go to the stable release" (link to https://docs.kubestellar.io/release-0.21.0/). This refers to itself.
- Similar for every release.
- https://docs.kubestellar.io/release-0.21.1/ tells the reader "You're not viewing the stable release. Click here to go to the stable release" (link to https://docs.kubestellar.io/latest/). Note wording mismatch: "stable" in the words, "latest" in the link.
- We seem to be treating "main" as the "latest" release, which is wrong because it is not something that users can use (it is not actually a release).

### Steps To Reproduce

See above.

### Expected Behavior

Consistent behavior

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates the policy docs and website behavior to eliminate the concept of a "stable" release and equate "latest" with the highest semver regular release.

If accepted, this PR will need to be followed up with corresponding PRs to the existing release branches so that their version warning banner will behave as intended.

## Related issue(s)

This partly resolves #2019

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
Successfully tested with pushes to my fork.

BTW, did you know that if you disable the suppression of working on forks as follows, you get your own copy of the website? The one produced by my testing is at https://mikespreitzer.github.io/kcp-edge-mc . The versions `main`, `release-0.25`, and `release-0.24` were produced in testing this. I produced release 0.24 _after_ 9.25, in order to verify the ordering in `mike list` output. Here is how to disable the suppression of working on forks:

```shell
(venv) bash-3.2$ git diff release-policy-redux
diff --git a/.github/workflows/docs-gen-and-push.yml b/.github/workflows/docs-gen-and-push.yml
index aebecab87..586331f78 100644
--- a/.github/workflows/docs-gen-and-push.yml
+++ b/.github/workflows/docs-gen-and-push.yml
@@ -22,14 +22,14 @@ concurrency:
 
 jobs:
   generate-and-push:
-    if: github.repository_owner == 'kubestellar'
+    # if: github.repository_owner == 'kubestellar'
     name: Generate and push docs
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4.1.1
-        with:
-          token: ${{ secrets.GH_ALL_PROJECT_TOKEN }}
-          persist-credentials: 'true'
+        # with:
+          # token: ${{ secrets.GH_ALL_PROJECT_TOKEN }}
+          # persist-credentials: 'true'
   
       - run: git fetch origin gh-pages
```

**Comment by MikeSpreitzer** [comment]
Putting this new policy into effect also requires one manual step: an authorized one of us has to `mike set-default latest`.

**Comment by MikeSpreitzer** [comment]
I have done the `mike set-default latest`.

**Comment by ezrasilvera** [comment]
Thanks, looks good. 
/lgtm
/approve

**Pull request merged**
