### PR TITLE
🐛  Increase scripting timeouts to 1 day

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR increases the timeouts in `scripts/create-kind-cluster-with-SSL-passthrough.sh` and `scripts/create-kubestellar-demo-env.sh` to a day, because we are getting reports of very long times to pull the images. Note that `kubectl wait` insists on having _some_ timeout.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by clubanderson** [comment]
is this the only timeout?

**Review by clubanderson — COMMENTED** [review]
/lgtm
/approve

**Comment by MikeSpreitzer** [comment]
These are the timeouts that I know about and have been having trouble with.

**Pull request merged**
