### PR TITLE
:book: Add Helm to required packages

### PR DESCRIPTION
**Pull request by namasl**
## Summary

Instructions for installing Helm are added to the required packages documentation.

## Related issue(s)

This addresses [#1017](https://github.com/kubestellar/kubestellar/issues/1017)

### CODE REVIEW

**Review by clubanderson — COMMENTED** [review]
/lgtm

**Comment by MikeSpreitzer** [comment]
@namasl : thank you for this.  Shouldn't Helm also be added to the general list?

**Review by MikeSpreitzer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
