### PR TITLE
📖 docs : Updating the contributor.md file by removing the height!

### PR DESCRIPTION
**Pull request by pratik-mahalle**
Signed-off-by: Pratik-Mahalle <mahallepratik683@gmail.com>

## Related issue(s)

Fixes #

### CODE REVIEW

**Review by MikeSpreitzer — COMMENTED** [review]
/lgtm

**Comment by ezrasilvera** [comment]
@pratik-mahalle Thank you for the PR
/approve

**Comment by MikeSpreitzer** [comment]
There was a Prow infrastructure problem.
/retest

**Pull request merged**
