### PR TITLE
:bug: :book: Update prereqs Fedora commands and quickstart.md

### PR DESCRIPTION
**Pull request by KPRoche**
## Summary
Updated Fedora family linux commands in docs/content/common-subs/required_packages.md include file
Also added a first "general" tab in that include file listing the packages without specific environments
Updated docs/content/Getting-Started/quickstart.md to include required packages in install flow
Moved anchor/heading # 1 out of included file and into docs/content/Getting-Started/quickstart.md
## Related issue(s)
700, 602
Fixes #
quickstart_page_preview

### CODE REVIEW

**Comment by KPRoche** [comment]
It appears docs-ecutable test is failing because of the bootstrap.sh issue #760

**Review by clubanderson — COMMENTED** [review]
/lgtm

**Comment by clubanderson** [comment]
I think you need to rebase to pickup the latest changes from Franco that made the quickstart work again.

**Review by clubanderson — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
