### PR TITLE
🐛 Cope with simplicity of SimpleClientset

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR makes a fix to the unit test of the mailboxwatch patckage.  The fix updates the checking of the Workspace informer behavior to cope with the fact that the fake clientset constructed by NewSimpleClientset has a dumb implementation of WATCH: it does not deliver the pre-existing objects.

This test still fails.  A full fix would require making a fake clientset whose LIST and WATCH behavior have full fidelity to ResourceVersion semantics.  The use of those semantics is an important part of what we want to test.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by waltforme** [comment]
@MikeSpreitzer Should this PR be reviewed now or be reviewed when the 'full fix' is done?

**Comment by MikeSpreitzer** [comment]
@waltforme: I do not think that the full fix is a high priority for us, so I would like to get this reviewed now.

**Comment by waltforme** [comment]
@MikeSpreitzer OK, will do.

**Pull request merged**
