### PR TITLE
🐛  Update best-practices.md to update the spelling of Kubernetes

### LINKED ISSUE #2222: bug: Kubernetes spelled wrong
### Describe the bug

Screenshot 2024-06-20 at 10 34 30 AM
In this above image, under the subsection "Size considerations" the second instance of Kubernetes is incorrectly spelled. 

### Steps To Reproduce

[https://docs.kubestellar.io/release-0.23.0/direct/best-practices/](https://docs.kubestellar.io/release-0.23.0/direct/best-practices/)
this is the website with the incorrect spelling

### Expected Behavior

Kuberentes should be spelled Kubernetes

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rchen-devv**
fixes #2222

## Related issue(s)

Fixes #2222

### CODE REVIEW

**Comment by clubanderson** [comment]
thanks for the fix - let me have a look

**Review by MikeSpreitzer — COMMENTED** [review]
/lgtm
Thanks!

**Comment by KPRoche** [comment]
A note -- this _is_ fixed in the file on the new website from PR #2229 but that doesn't display at kubestellar.io yet

**Comment by clubanderson** [comment]
@rchen-devv the new site was published a few hours ago. Check if this spelling is fixed already. If so, close this PR. You still get credit for the PR!

**Comment by KPRoche** [comment]
> @rchen-devv the new site was published a few hours ago. Check if this spelling is fixed already. If so, close this PR. You still get credit for the PR!

Note that until the next release triggers a render, the new site can be previewed at https://kproche.github.io/kubestellar/doc-new-v2

And this page in particular is at https://kproche.github.io/kubestellar/doc-new-v2/direct/best-practices/

**Comment by rchen-devv** [comment]
Just checked out the new site and its look good to me. Will close this PR.

**Pull request closed without merging**
