### PR TITLE
:book: Restore and Update installation info for go in required packages documentation

### PR DESCRIPTION
**Pull request by KPRoche**
## Summary
Restore notes about installing go as a prerequisite if the user intends to build kubestellar locally

Instructions for all OS tabs were added to the file

##  in response to issue #1026 

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
The new instructions are only for human reading, not docs-ecutable running in bash, right? That would be different from the other instructions; is that deliberate?

**Comment by MikeSpreitzer** [comment]
Also, as a general rule: if I already have something installed by a different package manager, please do not do an additional install.

**Comment by KPRoche** [comment]
> The new instructions are only for human reading, not docs-ecutable running in bash, right? That would be different from the other instructions; is that deliberate?

Yes. As I was reading the assorted instructions on the go website, it was abundantly clear that go is SUPER fussy about how it is installed (or re-installed). So I copied the instructions for different OS configurations from there as well as referring back to that page.

**Review by clubanderson — COMMENTED** [review]
/lgtm

**Comment by MikeSpreitzer** [comment]
And the GitHub workflows cover for go by having a step that installs it.
I wonder if there is a GitHub action that installs ko?

/approve

**Pull request merged**
