### PR TITLE
⚠️ Increment major version in Kubernetes API objects

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR increments the major version of the kube API for multi-cluster configuration management. We have made breaking changes since the last release, and it is normal to increment the major version in that case. Also, this is part of responding to #1058 .

I simply changed the version on the whole API. I did not worry about supporting a user who wants to do a rolling upgrade, because I think we have none of those.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
CI successfully ran example1 with deployment as bare processes.
I just successfully ran example1 with deployment to a kind cluster on my laptop.

**Comment by yana1205** [comment]
I also see no issue from the results of unit test/e2e test. I can approve this change but I'm not sure the current strategy to support backward compatibility in KubeStellar. If it's OK with supporting only v2alpha1, I'm fine with this PR. (I understand that supporting both versions at the development phase is too much effort to go forward.)

**Comment by yana1205** [comment]
/lgtm

I also see no issue from the results of unit test/e2e test so the change looks good to me.

However, I'm not sure the current strategy to support backward compatibility in KubeStellar. I understand that supporting both versions at the development phase is too much effort to go forward.

**Comment by MikeSpreitzer** [comment]
Currently we explicitly do NOT support any backward compatibility. So that is part of why this change is good to do now. Both because it is not harmful, and because NOT incrementing the major version would generate unnecessary confusion in users.

**Review by clubanderson — APPROVED** [review]
/approve

**Pull request merged**
