### PR TITLE
🐛  Update core-chart.md so that "|| true" is deleted to avoid redundancy

### PR DESCRIPTION
**Pull request by JonathanWentaoBao**
fixes Issue #2314 

## Related issue(s)

Fixes #

### CODE REVIEW

**Review by clubanderson — COMMENTED** [review]
/lgtm
/approve

**Comment by clubanderson** [comment]
@JonathanWentaoBao Thank you - please checkout and amend with signature - patch-5

**Comment by MikeSpreitzer** [comment]
FYI, https://github.com/kubestellar/kubestellar/issues/2314#issuecomment-2221774890

**Pull request merged**
