### PR TITLE
🐛 Update examples to track Placement schema change

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates the Placement objects exhibited in the doc to track #1525 .

Remember that users do not see the new schema until other things have changed (image, Helm chart, KubeFlex hook).

This PR also fixes the test for Helm labels.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
This merge looks premature to me.  https://github.com/kubestellar/kubestellar/tree/ks-0.20/docs/content/v0.20 still says `kflex create wds1 -p kslight`.

**Comment by ezrasilvera** [comment]
We switched to use the description under test/

**Pull request merged**
