### PR TITLE
✨ Prep for release 0.23.0-rc2

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates the self-references in preparation for release 0.23.0-rc2.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
It looks like the testing here revealed a flake. I reported the flake as #2201 . All the tests are now passing.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer The PR itself is OK, however this is becoming a tedious process where for each new version we need to update 6-7 files. (cc: @pdettori )

**Comment by MikeSpreitzer** [comment]
@ezrasilvera: Yes, it is tedious!  I have long expressed my loathing for self-references.

**Comment by MikeSpreitzer** [comment]
The force-push to 530f6dd2e is a rebase onto `main`.

**Pull request merged**
