### PR TITLE
🐛 Rebased update bootstrap and container image to use the patched kcp 0.11

### LINKED ISSUE #1248: feature: Update make-full-release, coreDockerfile, and bootstrap script to use the patched version of kcp
### Feature Description

Use the custom binaries for kcp
https://github.com/kubestellar/kubestellar/releases/download/v0.12.0/kcp_0.11.0_linux_amd64.tar.gz
https://github.com/kubestellar/kubestellar/releases/download/v0.12.0/kcp_0.11.0_linux_arm64.tar.gz
https://github.com/kubestellar/kubestellar/releases/download/v0.12.0/kcp_0.11.0_linux_ppc64le.tar.gz

### Proposed Solution

modify the curl urls in the bootstrap and codeDockerfile

### Want to contribute?

- [X] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR is #1249 but without the problematic merge of `main` into the PR's branch. I also added a commit that updates example1 to use the patched kcp when deploying bare processes.

## Related issue(s)

Fixes #1248

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
The syncer integration test is failing now. Note that since this PR includes a change to example1 to fetch and use the patched kcp, and the syncer integration test uses the same doc source, the syncer integration test is now using the patched version of kcp. That sounds right to me. So I do not understand why the syncer integration test should be failing.

**Comment by MikeSpreitzer** [comment]
I have updated this PR to be stacked on top of #1258, which I expect will merge first. Once that happens, I will rebase this PR onto `main`.

**Comment by MikeSpreitzer** [comment]
I did `make build-kubestellar-syncer-image` in the presence of commit 6b117020d17ea35c051f5cf0bce1ec6cf944001d and it produced `quay.io/kubestellar/syncer:git-6b117020d-clean@sha256:9197f2b43bcaf3318dfc2ead129e67c1f05c2785f921485aedd6fd72586d0d5b`.   I added tags `v0.14.0-alpha.1.git6b11702-clean` and `release-0.14`. Then I changed the default image tag in `outer-scripts/kubectl-kubestellar-prep_for_syncer` to `release-0.14`, that is the change in the last commit here now.

**Comment by francostellari** [comment]
@MikeSpreitzer please add that it fixes issue #1248 so that it gets closed automatically

**Comment by MikeSpreitzer** [comment]
The force-push to 81a8a0c9a is a rebase onto `main`.

**Comment by MikeSpreitzer** [comment]
Oh, actually the failure in the syncer integration test is because non-test material is being executed.

**Comment by MikeSpreitzer** [comment]
The "What KubeStellar syncer-gen plugin does" section of the syncer doc is outdated. It uses a _very_ old syncer image tag, and it is no longer right about the ServiceAccount's token.

**Comment by MikeSpreitzer** [comment]
PR #1263 should fix the problem with the syncer doc.

**Comment by MikeSpreitzer** [comment]
The force-push to 9f046270b restores the ability to run example1 on darwin, thanks to @pdettori building most of the patched kcp archives needed for that OS.

**Comment by MikeSpreitzer** [comment]
The force-push to 3854a685e is a rebase onto `main` to pick up the merge of #1263

**Pull request merged**
