### PR TITLE
⚠️ Update kcp dependency from v0.11.0 to v0.20.0

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates KubeStellar MCCM to depend on v0.20.0 of kcp rather than v0.11.0. This includes updating the import statements in the go sources, updating `go.mod`, and updating `kubestellar init` to setup the `root:compute` workspace like the TMC in kcp v0.11.0 did.

This should have several benefits. It moves KS MCCM to a later release of Kubernetes --- in particular, one that is maintained (see https://kubernetes.io/releases/), which 1.24 is not. BTW, this later version of Kubernetes seems to have fixed whatever was stopping the `--validate` flag to `kubectl apply` from working (which is why I was forced to include a fix to the where resolver example). This should also remove reasons to diverge from the upstream kcp Helm chart. And since this is the latest release of kcp, it should make it easier to get support and relevant changes from there too.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
I have tested successfully with the extended example, deploying the MCCM core as bare processes.  I have also built a new core image, which can be referenced as `quay.io/kubestellar/kubestellar:b23-10-02-03-36-02` and `quay.io/kubestellar/kubestellar: git-a3a8a3431-clean`; I will test that now.

**Comment by MikeSpreitzer** [comment]
My test of example1 with deploy-as-kube-workload succeeded.

**Comment by MikeSpreitzer** [comment]
OK, that image was bogus, core.Dockerfile has not been updated yet.

**Comment by MikeSpreitzer** [comment]
testing the core image showed that some more waiting needed to be added in entry.sh

**Comment by yana1205** [comment]
@MikeSpreitzer 
I created a PR (https://github.com/MikeSpreitzer/kcp-edge-mc/pull/2) to this branch for fixing Syncer E2E codes.
Could you please review and approve it?

**Comment by yana1205** [comment]
Sure, thank you very much for your help even at very early morning!

**Comment by clubanderson** [comment]
I am going to close this for now  @MikeSpreitzer. This is not an option for our project and having this PR open gives off the wrong smell.

**Pull request closed without merging**
