### PR TITLE
✨ Fix up some naming and comments in workload projector

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR does some cleanup in the workload projector source.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@clubanderson : the failure here from SonarCloud is from complaints about things that this PR is not touching.  SonarCloud seems to be annoyed about the code that is already merged.  Can we please get the improvements in this PR merged without being held-up by pre-existing issues?  I would be OK with a formal Issue being opened to address what SonarCloud is complaining about, but fixing that should be separate from this PR and should not hold up this PR.

**Comment by clubanderson** [comment]
@MikeSpreitzer - ok - open the issue(s) to care for the sonarcloud complaints found herein, add links to the issue(s) here in this PR, and then lets skip the sonarcloud test by overriding tide.  Let me know if this plan works for you for this PR.

**Comment by clubanderson** [comment]
ok - skipping tide now
/override tide

**Comment by clubanderson** [comment]
skipping tide did not work, but going into sonarcloud ui and closing the 2 issues did work.

**Pull request merged**
