### PR TITLE
✨ Return reported state from singletons if requested

### LINKED ISSUE #772: Special case for binding to exactly one workload execution cluster
### Discussed in https://github.com/kubestellar/kubestellar/discussions/703

<div type='discussions-op-text'>

<sup>Originally posted by **MikeSpreitzer** June 28, 2023</sup>
While an EdgePlacement generally binds to an arbitrary number of workload execution clusters, there is a significant body of usage in which that number is intended to be exactly 1.  In this case there is no summarization problem; the source object's status section is properly designed to handle this case and arguably the reported state should propagate back to there.</div>

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR introduces an API and implementation for #772 .

This is built on #1008 and would be rebased if that merged first.

## Related issue(s)

Fixes #772

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
The force-push to 3b8c5cb9e is a rebase onto `main`.
I am deliberately leaving the linter junk to the end.

**Comment by MikeSpreitzer** [comment]
This is now passing the updated example1 test, which tests for proper returns of executing object count and reported state.

**Comment by MikeSpreitzer** [comment]
The force-push to bcd09b275 updates some commentary and restores the (lack of) debugging in example1.

**Comment by clubanderson** [comment]
@namasl are you up to the challenge?  Would you like to test this PR?

**Comment by clubanderson** [comment]
@MikeSpreitzer please close if this is no longer active.

**Comment by clubanderson** [comment]
you can reopen if need be.

**Comment by MikeSpreitzer** [comment]
I think we prefer #1031

**Pull request closed without merging**
