### PR TITLE
📖 Clarify remarks about GoDaddy and redirects

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates docs/README.md to clarify the fact that we have two websites and how the redirects work.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by clubanderson** [comment]
@MikeSpreitzer please add my email address next to my name 'andy@clubanderson.com' (or you can make this a url - mailto://andy@clubanderson.com - up to you)

**Comment by MikeSpreitzer** [comment]
@clubanderson: see #2142

**Pull request merged**
