### PR TITLE
✨ Create generic command to execute a go template

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR adds a utility command that simply executes a given go template with some given data.

It can be helpful in developing Helm charts, and can be used in preliminary development before there is an actual Helm chart.  It can remove the need to make many variants of one config file.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
/cc @francostellari 
/cc @waltforme 
/cc @dumb0002 
@KPRoche

**Comment by waltforme** [comment]
I tried it. Just one small thing: Maybe we need a few newlines (e.g., at line 85) to make the stderr cleaner?
```
👉 kubestellar $ ./go-template-execute ~/tmp/todo.tmpl --data-json '{"User": "Jun"}' --data-field-yaml List=@/Users/junduan/tmp/list.yaml
<!DOCTYPE html>
<html>
  <head>
    <title>Go To-Do list</title>
  </head>
  <body>
    <p>
      To-Do list for user: Jun 
    </p>
    <table>
      	<tr>
          <td>Task</td>
          <td>Done</td>
    	</tr>
      	
			
      			<tr>
              		<td>Failed to execute template "/Users/junduan/tmp/todo.tmpl" on map[List:map[List:[map[Done:false Name:kill the bug] map[Done:no Name:fry the eggs]]] User:Jun]: template: todo.tmpl:18:23: executing "todo.tmpl" at <.Name>: can't evaluate field Name in type interface {}👉 kubestellar $ echo $?
80
```

**Comment by MikeSpreitzer** [comment]
The force-push to 88d384da adds some missing line terminators.

**Pull request merged**
