### PR TITLE
✨ Self-ref prep for test release 0.25.0-alpha.1.test.1

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates the self-references in preparation for test release 0.24.0-alpha.1.test.1.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by francostellari** [comment]
/lgtm

I don't think we use `config/postcreate-hooks/kubestellar.yaml` anymore since the test is via the helm chart

**Comment by MikeSpreitzer** [comment]
@francostellari : there are several vestigial things still present.

**Pull request merged**
