### PR TITLE
✨ Update values.yaml image tag to `latest`

### PR DESCRIPTION
**Pull request by francostellari**
## Summary

Update values.yaml image tag to latest

## Related issue(s)

Fixes #

### CODE REVIEW

**Review by clubanderson — COMMENTED** [review]
/lgtm
/approve

**Comment by MikeSpreitzer** [comment]
I think that this is a bad idea. It invites users to make Deployment objects using the image tag "latest". Doing that means that any work we do concurrently can sabotage that user, assuming we update what "latest" means.

The idea behind "release-0.9" is that it identifies a _release branch_ . That is not one point release, it is a branch of development that only includes backward-compatible changes.

**Comment by MikeSpreitzer** [comment]
For a point of comparison, see https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/

@francostellari : are you recommending that users always override the `image.tag` setting?

**Comment by clubanderson** [comment]
/lgtm
/approve

we can always change this to something else in the future if it does not serve us well.

**Comment by clubanderson** [comment]
@francostellari please rebase so this can merge

**Comment by MikeSpreitzer** [comment]
This is moot now.

**Pull request closed without merging**
