### PR TITLE
🐛 Fix over-broad input to controller-gen

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR narrows the inputs that controller-gen looks at, so that it no longer picks up the examples that `make codegenclients` puts in `hack/tools`.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
Something is broken here (and not in `main`).

```
mspreitz@mjs13 kubestellar % git status
On branch fix-paths
Your branch is up to date with 'origin/fix-paths'.

nothing to commit, working tree clean

mspreitz@mjs13 kubestellar % rm api/edge/v1alpha1/zz_generated.deepcopy.go 

mspreitz@mjs13 kubestellar % git status
On branch fix-paths
Your branch is up to date with 'origin/fix-paths'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    api/edge/v1alpha1/zz_generated.deepcopy.go

no changes added to commit (use "git add" and/or "git commit -a")

mspreitz@mjs13 kubestellar % make generate
/Users/mspreitz/go/src/github.com/kubestellar/kubestellar/bin/controller-gen object:headerFile="hack/boilerplate/boilerplate.go.txt" paths="api/..."

mspreitz@mjs13 kubestellar % git status
On branch fix-paths
Your branch is up to date with 'origin/fix-paths'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    api/edge/v1alpha1/zz_generated.deepcopy.go

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by MikeSpreitzer** [comment]
The force-push to 694169c4b fixes the above problem.

**Review by pdettori — APPROVED** [review]
/lgtm

**Pull request merged**
