### PR TITLE
:book: Minor formatting tweaks to architecture docs

### PR DESCRIPTION
**Pull request by jewzaam**
## Summary

Fixed some bullet formatting in the architecture document to resolve inconsitency between the intent (from the markdown) vs the rendered docuemntation.

## Related issue(s)

None

### CODE REVIEW

**Review by MikeSpreitzer — COMMENTED** [review]
/lgtm

Thanks!
But you need to sign the DCO before we can accept this.

**Comment by ezrasilvera** [comment]
@jewzaam Thanks for the PR. Can you please sign off your commit?  You can simply amend it .

**Comment by jewzaam** [comment]
@ezrasilvera thanks for the poke, missed that in my review of contributing guide.  done :)

**Comment by ezrasilvera** [comment]
Thanks for the PR
/approve

**Pull request merged**
