### PR TITLE
:bug: Physical Cluster -> Workload Execution Cluster swap

### LINKED ISSUE #1071: bug: mention of pcluster in output of our Kubestellar-prep-for-cluster
### Describe the bug

output of prep-for-cluster includes pcluster reference

`
Current workspace is "root:example-imw1".
--- current directory is /Users/andan02/projects/MCC/cicd/workloads/odh-operator-edgeplacement
current ws is root:example-imw1
imw is .
current cwsi is root:example-imw1
edge.kubestellar.io apibinding exists in workspace root:example-imw1
synctarget.edge.kubestellar.io/wec6 created
location.edge.kubestellar.io/wec6 created
synctarget.edge.kubestellar.io/wec6 labeled
location.edge.kubestellar.io/wec6 labeled
Current workspace is "root:example-imw1".
Current workspace is "root:espw".
Creating service account "kubestellar-syncer-wec6-2agyzzih"
Creating cluster role "kubestellar-syncer-wec6-2agyzzih" to give service account "kubestellar-syncer-wec6-2agyzzih"

 1. write and sync access to the synctarget "kubestellar-syncer-wec6-2agyzzih"
 2. write access to apiresourceimports.

Creating or updating cluster role binding "kubestellar-syncer-wec6-2agyzzih" to bind service account "kubestellar-syncer-wec6-2agyzzih" to cluster role "kubestellar-syncer-wec6-2agyzzih".

Wrote physical cluster manifest to wec6-syncer.yaml for namespace "kubestellar-syncer-wec6-2agyzzih". Use

  KUBECONFIG=<pcluster-config> kubectl apply -f "wec6-syncer.yaml"

to apply it. Use

  KUBECONFIG=<pcluster-config> kubectl get deployment -n "kubestellar-syncer-wec6-2agyzzih" kubestellar-syncer-wec6-2agyzzih

to verify the syncer pod is running.
Current workspace is "root:example-imw1".
Current workspace is "root".`

### Steps To Reproduce

1. run 'KUBECONFIG=~/ks.config kubectl kubestellar prep-for-cluster --imw root:example-imw1 wec6 env=wec6'
2. observe output

### Expected Behavior

replace 'pcluster' with 'workload execution cluster'

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by namasl**
## Summary
Updates old terminology `pcluster` with `wec`, and "physical cluster" with "workload execution cluster" or "WEC".

## Related issue(s)

Fixes #1071

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
This PR makes a change to an IDL file and it looks like `make codegen` has not been run. We maintain the files derived from the IDL in git, using `make codegen` to update them.

**Comment by clubanderson** [comment]
@namasl there are errors in the "pull-kubestellar-verify" test below.  You will need to look into them.  Click on the "details" link next to the test.

**Comment by namasl** [comment]
@clubanderson OK, I think I misunderstood @MikeSpreitzer. Upon looking at what the Makefile does, I should not be touching anything that `make codegen` generates and leave that action to happen on GitHub (rather than my last push, where I ran `make codegen`). Next push should undo all that.

**Comment by MikeSpreitzer** [comment]
Yes.  Use go 1.19 and `make codegen`

**Review by MikeSpreitzer — COMMENTED** [review]
The generated code is AOK now.
/lgtm
Thanks!

**Comment by namasl** [comment]
I ran `make codegen` with go 1.21.1 where I had originally seen an issue, but strangely I'm now seeing no difference between this and go 1.19.  I also checked 1.21.4 (latest), likewise no difference.

**Pull request merged**
