### PR TITLE
📖 Note dependency cycle between ks/ks and ks/OTP

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates packaging.md to be accurate about the current status of the ocm-transport-plugin and its dependency cycle with ks/ks.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by ezrasilvera** [comment]
@MikeSpreitzer not related to your changes - there are few inaccuracies  in the doc for example the OCM status addon image is not "is built and published using make"  but rather goreleaser.  Do we merge this PR and update the doc in following PRs ? (cc: @pdettori )

**Comment by MikeSpreitzer** [comment]
@ezrasilvera : yes, let's handle other inaccuracies in a separate PR. BTW, can you list them or characterize them (e.g., are they about recent changes in ocm-status-addon)?

**Pull request merged**
