### PR TITLE
📖 Update docs to use OTP Helm Chart

### PR DESCRIPTION
**Pull request by francostellari**
## Summary

Trying again to update docs to use OTP Helm Chart

Pending OTP chart 0.1.2 release

## Related issue(s)

Fixes #
https://github.com/kubestellar/kubestellar/issues/1866

### CODE REVIEW

**Comment by ezrasilvera** [comment]
@francostellari as we switched to 21.2-rc1 some rebase is needed.  I would solve the conflicts manually as they seems simple.
Most of the changes here are just coming from a leading space, can you please have a look?
BTW, if we remove the AGE column we would probably not have differences between runs (or it will be easier to see what was actually changed in the pods/objects created)  - currently all those lines are different because of the AGE

**Comment by MikeSpreitzer** [comment]
@francostellari : please do not merge `main` into a branch that you are going to submit in a PR against main; that mixes up the history. See https://docs.google.com/document/d/1iwkhpoV76-J-3G-Rif4B1cmL9SWBO_f_fE6WK8jvsDc

I created https://github.com/MikeSpreitzer/kcp-edge-mc/tree/updoc-franco-401 by just cherry-picking the one substantive commit here on top of `main` and resolving the one merge conflict.

**Comment by MikeSpreitzer** [comment]
Regarding the leading spaces: we have discovered that in order for the rendered GitHub pages to number the list items correctly, it is necessary to indent paragraphs of an item **4** spaces rather than 3.

**Comment by francostellari** [comment]
@nirrozenbaum thank you for releasing OTP chart v0.1.2!
The documented helm command appears to be working for me in Kind.
@MikeSpreitzer @ezrasilvera the PR is ready to merge.

**Comment by francostellari** [comment]
Replaced by #2003 2003

**Pull request closed without merging**
