### PR TITLE
🌱 Update inform-syncer-configs due to workspace flattening

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates the inform-syncer-configs demo/utility to track the removal of hierarchy in workspace usage (#1015). This demo/utility was usable, you just had to mentally adjust the instructions and naming.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by waltforme** [comment]
Hi @MikeSpreitzer the changes looks good to me. Just wanted to better understand the term 'workspace flattening' in the title.

The mailbox workspaces, after the changes in this PR, still has a 'parent' so the hierarchy is unchanged. So, how should I understand the term 'workspace flattening'?

**Comment by MikeSpreitzer** [comment]
By "flattening" I mean the change made in #1015 , which made every workspace that we use be a child of `root`.

**Comment by waltforme** [comment]
I see. Thanks for the pointer.

/lgtm
/approve

**Pull request merged**
