### PR TITLE
✨ Split user distro from full

### LINKED ISSUE #1055: feature: split kubestellar release into 'core' and 'plugins' to support helm and brew initiative
### Feature Description

Our release has all ks core plugins and ks kubectl plugins in the same tar archive.  These should be split out to allow for helm install of core components on kind, kubernetes, openshift, and plugins to install the complimentary plugins from the matching kubestellar release for kubectl using brew.

### Proposed Solution

1) split kubestellar release (from make file) into 2 parts.  core and plugins

### Want to contribute?

- [x] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR splits the scripts, build, and release archives so that there are release archives that exclude what goes in the core image.

This is not finished yet; the syncer e2e test is broken and the may be doc updates to do.

## Related issue(s)

Fixes #1055

### CODE REVIEW

**Review by clubanderson — COMMENTED** [review]
/lgtm

**Comment by MikeSpreitzer** [comment]
I successfully tested example1 by hand, deploying the core image to a kind cluster. I used a core image built from the branch here before the latest force-push, which was necessitated by a merge conflict with #1117 . The force-push to 9c1b98dc3c120e117cb9ff1c5c6501c2e53f8ff9 only changed one line in `kubectl-kubestellar-deploy`, which does not go into the core image. So I am confident that the test result still applies. While still wishing that we had automated this test.

**Comment by MikeSpreitzer** [comment]
This seems to be working now. Ready for final review and assent.

**Pull request merged**
