### PR TITLE
:book: Adding Cornell to the list of KubeStellar adopters.

### PR DESCRIPTION
**Pull request by rubambiza**
## Summary
Added Cornell University to the list of kubestellar adopters, though I had to take the scenic route on signing commits 😁 Wrt to gpg, I also wanted to share a [Stackoverflow fix](https://stackoverflow.com/questions/39494631/gpg-failed-to-sign-the-data-fatal-failed-to-write-commit-object-git-2-10-0) on how to deal with gpg signing errors (if installed using brew on macOS) in case it may be of use to other first-time committers to the repo.
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by rubambiza** [comment]
Oh boy! Was I supposed to pass some other flags to the commit command besides the message? I had set up my git such that [commits are automatically signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-gpg-key) as suggested by @MikeSpreitzer. If so, Mike can you please resend me the recipe you had suggested last time to amend the commit?

**Comment by MikeSpreitzer** [comment]
The commit is "verified" in the GitHub sense (https://docs.github.com/en/authentication/managing-commit-signature-verification).

image

**Comment by MikeSpreitzer** [comment]
Being GitHub "verified" implies that the commit is "signed". What is lacking is "sign-off", which is different from "signing" (sorry, I did not make up this terminology, I just have to live with it). At the start of https://docs.kubestellar.io/release-0.26.0-alpha.3/direct/pr-signoff/#pull-request-sign-off we have a brief note about this.

"sign-off" means that there is a line in the commit message that asserts sign-off. You can look at commits already in `main` for examples. You won't see it in the merge commits, you will see it in the ordinary commits. You can see the list of commits at https://github.com/kubestellar/kubestellar/commits/main/ . For a recent example of a signed-off commit, see https://github.com/kubestellar/kubestellar/commit/7c8549c404d4c0e99fbf9e7ea707c4276d5d1757 .

As for the Git CLI, following are two excerpts from the voluminous output from `man git-commit` on my machine.

```
       -s, --signoff, --no-signoff
           Add a Signed-off-by trailer by the committer at the end of the
           commit log message. The meaning of a signoff depends on the project
           to which you’re committing. For example, it may certify that the
           committer has the rights to submit the work under the project’s
           license or agrees to some contributor representation, such as a
           Developer Certificate of Origin. (See
           http://developercertificate.org for the one used by the Linux
           kernel and Git projects.) Consult the documentation or leadership
           of the project to which you’re contributing to understand how the
           signoffs are used in that project.
```

and

```
       -S[<keyid>], --gpg-sign[=<keyid>], --no-gpg-sign
           GPG-sign commits. The keyid argument is optional and defaults to
           the committer identity; if specified, it must be stuck to the
           option without a space.  --no-gpg-sign is useful to countermand
           both commit.gpgSign configuration variable, and earlier --gpg-sign.
```

**Comment by MikeSpreitzer** [comment]
To fix this commit you could use the following Git command line recipe on the same machine that you used to create the `add-cornell-to-adopters` branch for this PR.

```shell
git checkout add-cornell-to-adopters
git pull
git commit -s -S --amend # this will pop up an editor, allowing you to make edits to the commit message, I expect that you will need none, just exit the editor, this will return control to git
git push
```

The `-s` is what says to "sign off", and the `--amend` means to modify the current commit rather than make a new one.

**Comment by rubambiza** [comment]
Thanks for the guidance @MikeSpreitzer! The terminology is a bit convoluted, indeed. I'd assume a verified commit is automatically signed-off by the committer, especially since they provide the option to automatically sign. In the future, I will adjust my `alias gcom='git commit'` to `alias gcom='git commit -s'` to avoid this issue. Happy holidays!

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
