### PR TITLE
✨ Make kubestellar init create first IMW and WMW

### LINKED ISSUE #1048: feature: there should be at least 1 inventory and 1 workload management workspace created with KubeStellar by default
### Feature Description

KubeStellar is a bunch of parts that must be assembled before anything meaningful can be done with them.  

### Proposed Solution

In order to get closer to a useful solution it would be good to create 1 inventory and 1 workload management workspace created immediately following the containerized or non-containerized version of KubeStellar.

### Want to contribute?

- [ ] I would like to work on this issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR expands the functionality of `kubestellar init` to create an IMW and a WMW.

This PR is an alternative to #1052; unlike that one, this one does NOT build on #1042.

## Related issue(s)

Fixes #1048

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
/cc @clubanderson
/cc @dumb0002
@cwiklik
/cc @KPRoche
/cc @francostellari
@eaepstein

**Comment by MikeSpreitzer** [comment]
The force-push to 210181f0c fixes a bug in `kubestellar init` --- it was not stopping after just initializing.

**Comment by MikeSpreitzer** [comment]
The force-push to 211915976 is an attempt to fix that bug correctly.

**Comment by MikeSpreitzer** [comment]
The force-push to 0cd5cf07a attempts to make corresponding updates in the syncer doc.

**Comment by MikeSpreitzer** [comment]
I successfully went through example1 using kind clusters and deploying KS MCCM core to one of those kind clusters.  I tested the latest commit here (e6252fec5f2214f87b04e6d9e1992487f0b150e6), which means the core image used was quay.io/kubestellar/kubestellar:git-cf054b218-clean

**Comment by clubanderson** [comment]
@dumb0002 please review

**Comment by MikeSpreitzer** [comment]
The force-push above is a rebase onto `main`.

**Pull request merged**
