### PR TITLE
🐛 Update pre-reqs.md to fix spellings

### LINKED ISSUE #2267: bug: Inconsistent spelling of prerequisite
### Describe the bug

Prereqs_Screenshot

On the prerequisites page, the spelling is different in some places. It is inconsistent and uses both "pre-requisite" and "prerequisite"

### Steps To Reproduce

1. Go to: https://docs.kubestellar.io/unreleased-development/direct/pre-reqs/#check-pre-requisites-for-kubestellar
2. Search for the words "pre-requisite" and "prerequisite" 

### Expected Behavior

The correct spelling would be "prerequisite" with no hyphens

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aishwarya-mathew**
Fixes issue #2267

## Related issue(s)

Fixes #2267

### CODE REVIEW

**Comment by ezrasilvera** [comment]
@aishwarya-mathew Thanks for the PR. Please sign the commit

**Comment by clubanderson** [comment]
@aishwarya-mathew you need to sign this PR before it can be merged

**Pull request merged**
