### PR TITLE
:book:  Added Cornell University to list of adopters

### LINKED ISSUE #2669: docs: add Cornell to adopters
Adding Cornell to the list of adopters of KubeStellar at the workload integration maturity.

### PR DESCRIPTION
**Pull request by rubambiza**
## Summary
:book:  Added Cornell University to the list of adopters with workload integration maturity.

## Related issue(s)

Fixes #2669

### CODE REVIEW

**Review by clubanderson — COMMENTED** [review]
/lgtm
/approve

**Comment by clubanderson** [comment]
@rubambiza you need DCO to continue - this means you need to sign your PR.  check out https://medium.com/@chen7128611/generating-new-gpg-and-ssh-key-for-pr-d4ba5090db0f

**Comment by rubambiza** [comment]
> @rubambiza you need DCO to continue - this means you need to sign your PR. check out https://medium.com/@chen7128611/generating-new-gpg-and-ssh-key-for-pr-d4ba5090db0f

@clubanderson I'm running into a bit of trouble trying to install GnuPG on my Mac. I verified that the checksum checks out using shashum, but I can't get past the MacOS guardrails 👇 
GnuPG-Install-Failure

**Comment by MikeSpreitzer** [comment]
I installed gpg using HomeBrew. I do not remember whether I had to do some additional arm-wrestling with MacOS, but gpg is usable by me now.

**Comment by rubambiza** [comment]
I installed GPG using brew (thanks for the pointer @MikeSpreitzer and @clubanderson ), and I added a GPG to my GitHub account. Do I have to refork the repo and resubmit the PR all over?

**Comment by vMaroon** [comment]
@rubambiza you can [undo the commit locally](https://stackoverflow.com/questions/927358/how-do-i-undo-the-most-recent-local-commits-in-git), make a new signed commit and force push.

**Comment by MikeSpreitzer** [comment]
Slow down, there is an easier way...

**Comment by MikeSpreitzer** [comment]
Here is what I see now:
image

**Comment by MikeSpreitzer** [comment]
So if I understand correctly, what you are trying to accomplish is just get a commit that is exactly like 3f0de9b07906abe5de1aa0d620e3e203173e4a0b but is both "signed off" and "signed". There is a simple way to do that. Following is a recipe that should do accomplish it, using the `git` command line. The key idea is "ammending" an existing commit. And removing the revert, which added commits rather than removing or replacing existing ones.

Oh, I see that you used a branch named "main". That's not a great choice, but I will work with it. I assume here that you intend your fork's branch "main" to be used for this PR.

Here I assume that you have a git "remote" named upstream that refers to the shared repo on github.

```shell
git fetch upstream
git checkout -B main 3f0de9b07906abe5de1aa0d620e3e203173e4a0b
git commit -s -S --amend # this will open an editor in which you can revise the commit message, do so if you like, then save and exit the editor, this will return control to git
# Now you have replaced 3f0de9b07906abe5de1aa0d620e3e203173e4a0b with a version that is signed off and signed. Next, push it to your fork on github
git push -f -u origin main
```

**Comment by rubambiza** [comment]
> Here is what I see now. I see three commits, none of them "[verified](https://docs.github.com/en/authentication/managing-commit-signature-verification)", and if I understand correctly what you want is exactly one commit and that one being "verified" (as defined by GitHub).
> 
> image

@MikeSpreitzer Yes, that is the intent.

**Comment by MikeSpreitzer** [comment]
@rubambiza: the recipe I gave above should accomplish that, if the assumptions stated in it are correct.

**Comment by clubanderson** [comment]
Probably easier to close this PR and open a new one that is signed from the start @rubambiza

**Comment by rubambiza** [comment]
@clubanderson Let me try @MikeSpreitzer's recipe first. If some of the checks are still unsuccessful, then I will restart with a fresh fork.

**Comment by rubambiza** [comment]
Unfortunately, it failed 👇 
Commit-Amend-Error
I will start afresh later, and I will make sure to name the branch for the PR something other than main.

**Comment by MikeSpreitzer** [comment]
If your problem is a gpg failure to write then I expect it will strike when you start over too.

BTW, text is more accessible and easier to work with than pictures.

**Comment by clubanderson** [comment]
closing this PR in anticipation of a new one. Thank you @rubambiza

**Pull request closed without merging**
