### PR TITLE
✨Added KubestellarUI

### PR DESCRIPTION
**Pull request by katamyra**
## Summary

This PR introduces the KubestellarUI, a React and Golang-based user interface aimed at enhancing KubeStellar's usability. While the code is in working order on my machine, it is still in an early stage with several known bugs and needs a better get started guide. The PR includes a basic installation guide to help contributors get the UI running on their systems. The primary goal of this PR is to get eyes on the UI and get more work done on the UI.

[Kubestellar Code](https://github.com/katamyra/KubestellarUI)

Any help would be appreciated!

### CODE REVIEW

**Comment by clubanderson** [comment]
@katamyra I think you need to add .bin to .gitignore and remove those files from your PR

**Comment by vMaroon** [comment]
@katamyra thank you for this effort!

Though I have to say that this repo does not seem like the right place for this contribution. It makes more sense to start a separate one that can later get adopted into the project's organization, or to extend the [galaxy](https://github.com/kubestellar/galaxy) repository to home such contributions (cc @clubanderson).

**Comment by clubanderson** [comment]
@vMaroon yes, we are debating the right home for this. The idea is to get something in as a PR and then discuss how to proceed. I suggest kubestellar/ui as possibility.

**Comment by francostellari** [comment]
@katamyra (cc @andreyod ) I'm having problems with `npm run...`:

```shell
 npm run dev -- --host 0.0.0.0

> kubestellarui@0.0.0 dev
> vite --host 0.0.0.0


  VITE v5.4.8  ready in 385 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://10.0.2.15:5173/
  ➜  Network: http://9.2.179.197:5173/
  ➜  Network: http://172.18.0.1:5173/
  ➜  press h + enter to show help
node:internal/process/promises:394
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/vagrant/kubestellar/KubestellarUI): [Error] Loading PostCSS Plugin failed: Cannot find module '/home/vagrant/kubestellar/KubestellarUI/node_modules/lines-and-columns/build/index.js'. Please verify that the package.json has a valid "main" entry

(@/home/vagrant/kubestellar/KubestellarUI/postcss.config.js)
Error: Loading PostCSS Plugin failed: Cannot find module '/home/vagrant/kubestellar/KubestellarUI/node_modules/lines-and-columns/build/index.js'. Please verify that the package.json has a valid "main" entry

(@/home/vagrant/kubestellar/KubestellarUI/postcss.config.js)
    at load (file:///home/vagrant/kubestellar/KubestellarUI/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:33602:11)
    at file:///home/vagrant/kubestellar/KubestellarUI/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:33627:16
    at Array.map (<anonymous>)
    at plugins (file:///home/vagrant/kubestellar/KubestellarUI/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:33626:8)
    at processResult (file:///home/vagrant/kubestellar/KubestellarUI/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:33696:14)
    at file:///home/vagrant/kubestellar/KubestellarUI/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:33826:14]

Node.js v23.4.0
```

Additional info:
- go version go1.23.3 linux/amd64
- npm 10.9.2
- node v23.4.0
- VITE v5.4.8
- Linux vagrant.local 5.15.0-126-generic #136-Ubuntu SMP Wed Nov 6 10:38:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by clubanderson** [comment]
I am using vite 5.4.11 - thats prolly your issue @francostellari 

```VITE v5.4.11  ready in 129 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.5.222:5173/
  ➜  press h + enter to show help```

**Comment by MikeSpreitzer** [comment]
Currently this PR is asking to contribute over 5000 files. If those are mostly not intended, then do please get them out of the PR.

Remember that in Git it does not work to update `.gitignore` in a later commit than one that introduces the files that you want to ignore. The update to `.gitignore` has to come first.

**Comment by clubanderson** [comment]
@MikeSpreitzer see my comments above re: too many files

**Comment by MikeSpreitzer** [comment]
@clubanderson: yes, I was trying to add a little detail about the update to `.gitignore`.

**Comment by clubanderson** [comment]
@katamyra added https://github.com/kubestellar/ui with the latest from your main branch. closing this PR so we can move over to that repo and continue working. Thank you for your contribution.

**Pull request closed without merging**
