### PR TITLE
✨ Improve post-test state dump

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR revises the state dump at the end of the test workflows, to more clearly separate the different parts.

This is in place of https://github.com/vMaroon/kubestellar/pull/9

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by ezrasilvera** [comment]
1. I'm not sure that separate the outputs into different sections is better for debugging usage, but will leave that for now.
2. Can we add some prefix to all this sections , anything reasonable is fine state-   debug- info-  summary-

**Comment by MikeSpreitzer** [comment]
The force-push to 18432f4d0 changes the job step names based on the review above.

**Comment by effi-ofer** [comment]
I am late to the party here seeing how this just got merged.  In the future it would be nice to also dump the list of deployments on the WEC clusters.

**Comment by MikeSpreitzer** [comment]
@effi-ofer : I agree. You could offer that in another PR.

**Pull request merged**
