### PR TITLE
✨ UX - Report what resolution

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR introduces a kind of API object for reporting the objects that match an EdgePlacement's "what predicate" and extends the placement controller to maintain these objects.

This PR is currently built on top of #1221. Once that merges, I will rebase this one.

## Related issue(s)

This is intended to address #909.

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
This is a backward-compatible change.

**Comment by MikeSpreitzer** [comment]
The force-push to a973815d9 is a rebase onto `main`.

**Comment by MikeSpreitzer** [comment]
The force-push to d0c3213b0 is a rebase and extends the reported info about each workload part to include the mode bits handled by the what-resolver.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer is this still relevant ?  ks-0.20 is using completely different code, right ?

**Comment by MikeSpreitzer** [comment]
@ezrasilvera : the API part is still relevant, even though the implementation part needs major adaptation.

**Pull request closed without merging**
