### PR TITLE
✨  Add Binding objects to snapshot output

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR extends the snapshot script to dump the Binding objects too.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by francostellari** [comment]
- stylistically rest of the script uses 2 line spaces to separate blocks
- I suggest replacing COLOR_RED with either COLOR_ERROR|COLOR_WARNING in case down the line somebody changes the color scheme

**Comment by MikeSpreitzer** [comment]
I revised the way Binding objects are listed: now the normal listing enumerates the objects, and in the case of empty cross product it shows the reason(s) why, and there is no longer an empty namespace listed for cluster-scoped objects. Following is a picture of example output.

image

**Comment by francostellari** [comment]
/lgtm
Thank you

**Pull request merged**
